server:
    # running mode.
    mode: debug
    # running port.
    port: 8101
    # ca for making certs. DON'T TRUST THIS CERT OR YOU MAYBE DATA LOST!
    cacert: ca.pem
    # key for making certs. DON'T TRUST THIS CERT OR YOU MAYBE DATA LOST!
    cakey: ca.key
general:
    # steam mode. If open this, patch will open game with REGISTER KEY CHANGED.
    # If not work, just try Administrator mode.
    hookmode: true
    # steamid, you should fill this to unlock evolve2 with your legal game. default is 76561101839859666.
    steamid: 76561101839859666